### ISSUE TITLE
Adjusting qualifier when creating new stages

### ISSUE THREAD

**Issue by TimPaisley** [BrianFarnhill/Demos.CDKApiPipeline#5]
Not sure if this is something I did wrong when bootstrapping my environments or setting up this project, but whenever I deployed I kept getting the following error when trying to create the KMS key.

> Policy contains a statement with one or more invalid principals.

To solve this, I changed `'apidemo'` to the default qualifier `'hnb659fds'` when adding the stages in `PipelineStack.ts`.

https://github.com/BrianFarnhill/Demos.CDKApiPipeline/blob/9e206a15c1b67a529af9d8a56bac7cd9f7f7912e/lib/PipelineStack.ts#L93

Just thought it might be worth mentioning.

**Comment by BrianFarnhill** [comment]
Hey @TimPaisley - thats my bad. I had some weird bootstrapping issues in my account that warranted the qualifier, and I didn't get back around to removing it again. I should be able to tidy that back up this week, I'll close this off once it's dealt with though. The `hnb659fds` value is the default qualifier that CDK uses - and normally when you don't specificy a synthesiser that's what comes out.

**Comment by BrianFarnhill** [comment]
Hey @TimPaisley - pushed a few changes today that should do the trick for you, see [this commit](https://github.com/BrianFarnhill/Demos.CDKApiPipeline/commit/0218cd65aaa2bb48ed5cde702ed7457407a22ee9) for the specific change. I'll close this one off now but if you have other issues let me know.
